### ISSUE TITLE
NullPointerException when MappingFactory.Factory is used to create MappingContext

### ISSUE THREAD

**Issue by miras108** [orika-mapper/orika#172] opened 2016-12-13 13:47 UTC
The following error occurred when MapperFacade.map(..) method was  invoked with MappingContext object created by MappingContext.Factory().getContext() method:

`java.lang.NullPointerException
	at ma.glasnost.orika.impl.generator.MapperGenerator.build(MapperGenerator.java:104)
	at ma.glasnost.orika.impl.DefaultMapperFactory.buildMapper(DefaultMapperFactory.java:1333)
	at ma.glasnost.orika.impl.DefaultMapperFactory.lookupMapper(DefaultMapperFactory.java:718)
	at ma.glasnost.orika.impl.MapperFacadeImpl.resolveMapper(MapperFacadeImpl.java:572)
	at ma.glasnost.orika.impl.MapperFacadeImpl.resolveMappingStrategy(MapperFacadeImpl.java:179)
	at ma.glasnost.orika.impl.MapperFacadeImpl.map(MapperFacadeImpl.java:675)`

The problem is because MappingContext.Factory creates Context with empty globalProperties elements. 
When there is no CAPTURE_FIELD_CONTEXT property following line in SourceCodeContext.java class constructor causes NullPointerException:

`this.shouldCaptureFieldContext = (Boolean) mappingContext.getProperty(Properties.CAPTURE_FIELD_CONTEXT);`

The shouldCaptureFieldContext variable is a boolean type and cannot be set as a null.

This issue occurred when orika-core was upgrade from 1.4.5 version to 1.5.0 version.
Do You know some workaround for this problem? 
Can we expect fix for this issue in next release?

Thanks & Regards,
Piotr

**Comment by mfriessen** [comment] 2016-12-17 02:05
I am also seeing the same exception after upgrading.

**Comment by brabenetz** [comment] 2016-12-17 09:46
I have difficulty to reproduce the error.

How do you create your MapperFactory?
MapperFactory factory = new DefaultMapperFactory.Builder().build();

Or have you your own implementation of the MappingContextFactory?

**Comment by miras108** [comment] 2016-12-19 08:28
Hi, 
Yes, I'm using DefaultMapperFactory.Builder().build method to create MapperFactory. 
I created test to recreate this problem:

```
@Test
    public void orikaMappingTest()
    {
        String key = "Key";
        String value = "Value";

        A source = new A();
        source.setKey(key);
        source.setValue(value);

        DefaultMapperFactory mapperFactory = new DefaultMapperFactory.Builder().build();
        MappingContext context = new MappingContext.Factory().getContext();

        B result = mapperFactory.getMapperFacade().map(source, B.class, context);

        assertThat(result.getKey()).isEqualTo(key);
        assertThat(result.getValue()).isEqualTo(value);
    }
```

And the result of running this test:

`ma.glasnost.orika.MappingException: While attempting the following mapping:
sourceType = orika.test.A
destinationType = orika.test.B
Error occurred: java.lang.NullPointerException
	at ma.glasnost.orika.impl.generator.MapperGenerator.build(MapperGenerator.java:104)
	at ma.glasnost.orika.impl.DefaultMapperFactory.buildMapper(DefaultMapperFactory.java:1333)
	at ma.glasnost.orika.impl.DefaultMapperFactory.lookupMapper(DefaultMapperFactory.java:718)
	at ma.glasnost.orika.impl.MapperFacadeImpl.resolveMapper(MapperFacadeImpl.java:572)
	at ma.glasnost.orika.impl.MapperFacadeImpl.resolveMappingStrategy(MapperFacadeImpl.java:179)
	at ma.glasnost.orika.impl.MapperFacadeImpl.map(MapperFacadeImpl.java:675)
	at orika.test.OrikaTest.orikaMappingTest(OrikaTest.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:130)
Caused by: java.lang.NullPointerException
	at ma.glasnost.orika.impl.generator.SourceCodeContext.<init>(SourceCodeContext.java:105)
	at ma.glasnost.orika.impl.generator.MapperGenerator.build(MapperGenerator.java:66)
	... 37 more`

Regards,
Piotr

**Comment by brabenetz** [comment] 2016-12-19 18:12
The MappingContext.Factory is normally initialized by the DefaultMapperFactory constructor.

I think a clean workaround would be:
```Java
MappingContext.Factory mappingContextFactory = new MappingContext.Factory();
MapperFactory factory = new DefaultMapperFactory.Builder()
    .mappingContextFactory(mappingContextFactory)
    .build();
MappingContext context = mappingContextFactory.getContext();
```

Maybe there are other site-effects (even if the NullPointerException will be fixed), if you use it your way.
I will look into it.

**Comment by thermech** [comment] 2017-03-19 02:54
I'm using version 1.4.6 and when I tried to upgrade to 1.5.0 I got the same error. The problem seem to be that all globals properties are empty but was filled with default values in older version. 

I create the context like this:
`MappingContext context = new MappingContext.Factory().getContext();`

I'm talking about those properties:

```
COMPILER_STRATEGY
CAPTURE_FIELD_CONTEXT
PROPERTY_RESOLVER_STRATEGY
FILTERS
CODE_GENERATION_STRATEGY
MAPPER_FACTORY
UNENHANCE_STRATEGY
SHOULD_MAP_NULLS
```

Now (in 1.5.0) the globalProperties are empty. Why ?

We have no choice but to rollback for now

**Comment by rajcspsg** [comment] 2018-06-12 22:18
I'm also having the same problem. It works fine with 1.4.6 version but fails when updated to 1.5.2.

Any workaround to set these properties manually?

**Comment by blaluc** [comment] 2018-10-23 17:38
Any chance to fix this issue or should I downgrade to 1.4.6 in order to use a MappingContext?

**Comment by igorbljahhin** [comment] 2019-04-14 14:09
I can confirm, that instantiating of MappingContext as described in https://github.com/orika-mapper/orika/issues/172#issuecomment-268035945 and upgrading Orika to version 1.5.4, solved my issue.

**Closed** 2019-04-16 09:10 UTC

**Comment by gpc539** [comment] 2020-07-30 11:10
Same issue is coming for me 
java.lang.NullPointerException at ma.glasnost.orika.impl.generator.MapperGenerator.build(MapperGenerator.java:104) at ma.glasnost.orika.impl.DefaultMapperFactory.buildMapper(DefaultMapperFactory.java:1333) at ma.glasnost.orika.impl.DefaultMapperFactory.lookupMapper(DefaultMapperFactory.java:718) at ma.glasnost.orika.impl.MapperFacadeImpl.resolveMapper(MapperFacadeImpl.java:572) at ma.glasnost.orika.impl.MapperFacadeImpl.resolveMappingStrategy(MapperFacadeImpl.java:179) at ma.glasnost.orika.impl.MapperFacadeImpl.map(MapperFacadeImpl.java:675)

this.shouldCaptureFieldContext = (Boolean) mappingContext.getProperty(Properties.CAPTURE_FIELD_CONTEXT);

The shouldCaptureFieldContext variable is a boolean type and cannot be set as a null.

**Comment by Gabriel-fono** [comment] 2023-04-10 19:05
I need some 
I am trying to upgrading for Orika to the version 1.5.4.
@igorbljahhin claims #172 (comment) works for him.
I am not sure if anyone getting its Orika 1.5.4 works properly.
it is few days since I am trying to figure this out.
here is what I keep getting
at ma.glasnost.orika.impl.generator.SourceCodeContext.<init>(SourceCodeContext.java:89)
	at ma.glasnost.orika.impl.generator.MapperGenerator.build(MapperGenerator.java:66)
	... 28 common frames omitted
Wrapped by: ma.glasnost.orika.MappingException: java.lang.NullPointerException
	at ma.glasnost.orika.impl.generator.MapperGenerator.build(MapperGenerator.java:104)
	at ma.glasnost.orika.impl.DefaultMapperFactory.buildMapper(DefaultMapperFactory.java:1478)
	at ma.glasnost.orika.impl.DefaultMapperFactory.lookupMapper(DefaultMapperFactory.java:738)
	at ma.glasnost.orika.impl.MapperFacadeImpl.resolveMapper(MapperFacadeImpl.java:568)
	at ma.glasnost.orika.impl.MapperFacadeImpl.resolveMappingStrategy(MapperFacadeImpl.java:178)
	at ma.glasnost.orika.impl.MapperFacadeImpl.mapElement(MapperFacadeImpl.java:792)
	at ma.glasnost.orika.impl.MapperFacadeImpl.mapAsCollection(MapperFacadeImpl.java:622)
	at ma.glasnost.orika.impl.MapperFacadeImpl.mapAsList(MapperFacadeImpl.java:428)
	
	hope someone  finds something

**Comment by igorbljahhin** [comment] 2023-04-11 13:26
> ```java
> new MappingContext.Factory()
> ```

I do not remember exact issue, but I confirm, that we are using orika 1.5.4 as described in https://github.com/orika-mapper/orika/issues/172 since then.
